name: Android Build & Deploy

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.4' # Not needed with a .ruby-version file
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically

      - name: Decode Service Account Key JSON File
        uses: timheuer/base64-to-file@v1
        id: service_account_json_file
        with:
          fileName: "serviceAccount.json"
          encodedString: ${{secrets.GPLAY_SERVICE_ACCOUNT_KEY_JSON}}

      - name: Decode Keystore File
        uses: timheuer/base64-to-file@v1
        id: android_keystore
        with:
          fileName: "android_keystore.keystore"
          encodedString: ${{secrets.KEYSTORE_FILE}}

      - name: Create Client ID
        env:
          CLIENT_ID: ${{secrets.CLIENT_ID}}
        run: echo CLIENT_ID=$CLIENT_ID > ./local.properties

      - name: Accept Android SDK license
        run: echo "y" | /usr/local/lib/android/sdk/cmdline-tools/latest/bin/sdkmanager "build-tools;34.0.0"

      - name: Build & deploy Android release
        run: bundle exec fastlane deploy
        env:
          KEYSTORE_FILE: ${{steps.android_keystore.outputs.filePath}}
          STORE_PASSWORD: ${{secrets.KEYSTORE_PASSWORD}}
          KEY_ALIAS: ${{secrets.KEY_ALIAS}}
          KEY_PASSWORD: ${{secrets.KEY_PASSWORD}}
          ANDROID_JSON_KEY_FILE: ${{steps.service_account_json_file.outputs.filePath}}

      - name: Upload build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: assets
          path: |
            ${{github.workspace}}/app/build/outputs/bundle/release